### ISSUE TITLE
Pixelmon Reforged

### ISSUE THREAD

**Issue by itsHadez** [blairwilson/PixelChat#6]
Im using the command @pokeX (with slot number) and its not working. im currently running pixelmon 8.1.2. any solution?

**Comment by blairwilson** [comment]
Just installed fresh copy of: SpongeForge 7.3.0, Pixelmon 8.1.2, PixelChat 1.80 and no errors

https://i.imgur.com/CBhmQnM.png

**Comment by blairwilson** [comment]
Just installed fresh copy of: SpongeForge 7.3.0, Pixelmon 8.1.2, PixelChat 1.80 and no errors

https://i.imgur.com/CBhmQnM.png
